### ISSUE TITLE
Too tall option button doesn't scroll on arrow keys

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#2681]
Very likely a Godot bug, I'm opening this issue to track this (and hopefully get someone to check if this is reported to Godot as a bug already and open a bug report if not already open).

Basically when the option button popup is very tall and you use the arrow keys to move in the list, the highlighted item is not scrolled into view:
![2021-10-21_11 03 03 9377](https://user-images.githubusercontent.com/3796411/138237561-14798e9b-0efd-4ecc-bd27-168d8cf83337.png)
Here I pressed the up arrow and notice how now nothing seems to be selected (even though the item just off-screen is selected):
![2021-10-21_11 03 05 2872](https://user-images.githubusercontent.com/3796411/138237641-126ae2d6-6d9f-4546-a891-59b4150765d1.png)

If we report this to Godot it might be nice to also suggest adding a scrollbar to make it obvious to a user that there's more options.
Not super critical yet but for full controller support (I assume the same bug exists when using a controller) this is important to fix.

**Comment by hhyyrylainen** [comment]
Needs testing if Godot 4 fixed this problem.

**Comment by 0HyperCube** [comment]
@hhyyrylainen This was fixed by https://github.com/godotengine/godot/pull/80271.

**Comment by hhyyrylainen** [comment]
It's in 4.2 so I think this should be in Thrive already. I just tested and it now tries to work, but there's a bug still where it doesn't fully scroll:

![kuva](https://github.com/user-attachments/assets/185208ed-d3ae-48ca-b488-7ba383a44ac0)

I guess it would be fine to close this now and then report that as a separate engine bug (I'd really appreciate if someone else can do that as I need to catch up on 2 weeks of github emails...)
