### ISSUE TITLE
Editor button bars should go back to non-filled states when multicellular reproduction progress is lost

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3551]
so that they don't stay white when no longer being filled up. Also a related problem: https://github.com/Revolutionary-Games/Thrive/issues/3550

**Comment by dligr** [comment]
It seems like this issue has been fixed at some point along with as #3550 and #3211 (possibly by #4581). At least, I couldn't reproduce those issues in my testing (but it would be good if someone else could check this as well)

**Comment by hhyyrylainen** [comment]
From what I've seen recently, this is partially fixed: the bars reset when a new growth happens. So from what I remember I saw this: the bars update normally, but when a cell is lost the bars then just stop for a while and only after a new cell is grown the bars jump backwards to what they should be.

So yeah this kind of is not a totally major bug anymore, but still could do with some improvements.

I added the "immediately" word to the title to keep this issue still relevant.
