### ISSUE TITLE
[Bug][Linux] Ram usage increases with no limit

### ISSUE THREAD

**Issue by Marteon** [Revolutionary-Games/Thrive#506]
EDIT: This problem only occurs in the Linux version of the Game.

The Memory usage starts at about 190MB and as soon as you have control over the Cell the ram usage increases gradually. After about 40 Minutes of trying to reproduce a crash, all my 16GB of ram were used.

It increases at a rate of about 10-20 MB per second.

EDIT: The Memory leak doesn't stop when I am in the ingame "ESC"-Menu. But when I Exit to MainMenu the leak stops and continues when I play again.

**Comment by crodnu** [comment]
Are you sure you downloaded the full 0.3.3 release and not the 0.3.3 release candidate? I ask because we had a memory leak in our second release candidate but it was fixed in the full release. The version (in the lower right corner of the main menu) should say 0.3.3 and not 0.3.3 rc1.

**Comment by Marteon** [comment]
I am pretty sure that I downloaded the full 0.3.3 release but sadly it doesn't show the version number in the button right. It only shows a "v". I downloaded from (here)[https://github.com/Revolutionary-Games/Thrive/releases] (I also redownloaded and tested it out)

**Comment by hhyyrylainen** [comment]
I have this same issue and I have already tried using assets from the official windows release. 
So this is indeed still an issue on linux. I'll get around to this and the audio manager crash once I'm done with the new lua stuff.

**Comment by hhyyrylainen** [comment]
This was probably caused by the usage of cg shaders. I've removed them and no the memory usage doesn't seem to grow infinitely.
