### ISSUE TITLE
Fix new bug where cell "Gyrates" possibly caused by the fact that we have to place the nucleus now.

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#725]
The bug can be seen in this video:
https://www.youtube.com/watch?v=9oZjzrw2vEI
It is also in kinesis' most recent stream (which he hasn't posted yet)

**Comment by Untrustedlife** [comment]
Probably related to #721

**Comment by hhyyrylainen** [comment]
Isn't this fixed, at least for now, with the mass change?

**Comment by Untrustedlife** [comment]
Yep it’s fixed I was going to wait to close the issue until I merged though, the cell orientation bug is also fixed with that

**Comment by hhyyrylainen** [comment]
It doesn't actually fix the orientation. There is still the issue that the orientation slowly recovers. Though, the mass change also helped there, but that orientation was a bug even before removing the nucleus.

**Comment by Untrustedlife** [comment]
Fixed in #675
